### ISSUE TITLE
BridgeBBCC의 CSS를 제 프로젝트(ElecTwitch)에 적용하고자 합니다.

### ISSUE THREAD

**Issue by kyujin-cho** [krynen/BridgeBBCC#1]
정확히 말하면, 제 프로젝트의 플레이어 구조를 BridgeBBCC의 채팅 UI HTML 구조에 호환되게 수정하여
BridgeBBCC용으로 만들어진 CSS 테마들에 호환되게 바꾸고자 합니다.
혹시, BridgeBBCC의 기본 CSS를 제 프로젝트에 그대로 집어넣어도 될까요?
https://github.com/thy2134/ElecTwitch
제 프로젝트 링크입니다.

**Comment by krynen** [comment]
1.  bridgeBBCC의 기본CSS를 사용하시는 것은 어떤 형태로든 아무 문제 없습니다.

2. 확정된 사안은 아니지만 이후 버전에서 HTML 구조가 바뀔 가능성이 있음을 참고하셨으면 합니다.

바뀌든 안바뀌든 제가 작업을 빨리 진행해야 하는데 계속 개인사정은 쌓이고 얽힌 프로젝트만 많아지고있네요..

**Comment by kyujin-cho** [comment]
감사합니다.
