### ISSUE TITLE
심각한 문제는 아니고 궁금한게 있는데요

### ISSUE THREAD

**Issue by LocketGoma** [krynen/BridgeBBCC#7]
Dccon_list.js 파일의 기본 인코딩이 EUC-KR인거로 알고 있는데 맞나요?

이전에 리스트 에디터 테스트하다가 UTF-8로 저장되었던거 노트패드++에서 잘 열리길래 아무생각없이 넣었다가 하나도 안 들어가길래 문제가 있다는걸 발견하긴 했는데...

생각해보니 '아 이게 아닌갑다' 하고 쓰긴 했는데 정확히 무슨 인코딩인지 파악은 못했었네요. 답변 부탁드립니다.

**Comment by krynen** [comment]
utf-8입니다.
