### ISSUE TITLE
중복 구독티콘 사용 시 깨짐.

### ISSUE THREAD

**Issue by DevEruis** [krynen/BridgeBBCC#8]
**메인 이슈**
같은 구독티콘을 입력 시, 화면 내 채팅창 상에서 중복되는 구독티콘이 골라서 깨짐.
ex) BloodTrail BloodTrail (X)

**관련 테스트**

1. 다른 구독티콘을 1회씩 나열할 경우 (Squid1 Squid2 Squid3 Squid4)
 ⇒ 정상출력
2. 입력된 구독티콘 중 2회 이상 사용된 것이 포함된 경우 (Squid1 Squid2 Squid3 Squid2 Squid4)
⇒ 중복된 Squid2만 골라서 깨지고 나머지는 정상출력

**Comment by krynen** [comment]
수정 완료되었습니다 → d6341f9 ([v0.5.1](https://github.com/krynen/BridgeBBCC/releases/tag/v0.5.1)).
제보 감사합니다.
